gems:
  - jekyll-sitemap
  - jekyll-paginate

timezone: Europe/London

title: "Minecraft: Pocket Edition Modding"

excerpt_separator: <!--read more-->

collections:
  wiki:
    output: true
    permalink: /wiki/:path/
  tutorials:
    output: true
    permalink: /tutorials/:path/
 
defaults:
  - scope:
      path: ""
      type: pages
  - scope:
      path: ""
      type: wiki
  - scope:
      path: ""
      type: tutorials
    values:
      layout: page
      secondarytitle: MCPE Modding Wiki
