timezone: Europe/London

title: "Minecraft: Pocket Edition Modding"

pygments: true
markdown: redcarpet

collections:
  wiki:
    output: true
    permalink: /wiki/:path/
  tutorials:
    output: true
    permalink: /tutorials/:path/
 
defaults:
  - scope:
      path: ""
      type: pages
  - scope:
      path: ""
      type: wiki
    values:
      layout: page
  - scope:
      path: ""
      type: tutorials
    values:
      layout: page
